"""empty message

Revision ID: c9a5faaf6a28
Revises: 07e00bcbf2a0
Create Date: 2024-02-18 18:18:53.412724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a5faaf6a28'
down_revision = '07e00bcbf2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercart',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('bike_id', sa.String(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikeconfig.id'], ),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_cart')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('user_cart',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BikeConfigID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['BikeConfigID'], ['bikeconfig.id'], name='user_cart_BikeConfigID_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_cart_pkey')
    )
    op.drop_table('usercart')
    # ### end Alembic commands ###
